
DEFINE QLOCAL ('XML_FLIGHTQUERY_FLIGHT') REPLACE
DEFINE QLOCAL ('XML_FLIGHTQUERY_IN') REPLACE
DEFINE QLOCAL ('XML_FLIGHTQUERY_OUT') REPLACE
DEFINE QLOCAL ('XML_FLIGHTQUERY_PASSENGERS') REPLACE
DEFINE QLOCAL ('XML_FLIGHTQUERY_REPLIES') REPLACE
DEFINE QLOCAL ('XML_FLIGHTQUERY_TIMEOUT') REPLACE
DEFINE QLOCAL ('XML_FLIGHTQUERY_FAIL') REPLACE