connect to EMPLOYEE
drop table "DB2SCHEMA".PERSONAL_DETAILS
create table "DB2SCHEMA".PERSONAL_DETAILS(EMPNAME VARCHAR(25) NOT NULL, EMPNO BIGINT NOT NULL,AGE INT, SEX VARCHAR(10),MARITAL_STATUS VARCHAR(10),NATIONALITY VARCHAR (20), PRIMARY KEY(EMPNO))
INSERT into "DB2SCHEMA".PERSONAL_DETAILS VALUES('SAM',11111,25,'MALE','SINGLE','AMERICAN')
INSERT into "DB2SCHEMA".PERSONAL_DETAILS VALUES('ALEX',22222,45,'MALE','MARRIED','BRITISH')
INSERT into "DB2SCHEMA".PERSONAL_DETAILS VALUES('LAURA',33333,22,'FEMALE','SINGLE','INDIAN')
drop table "DB2SCHEMA".EMPLOYMENT_DETAILS
create table "DB2SCHEMA".EMPLOYMENT_DETAILS(EMPNAME VARCHAR(25) NOT NULL, EMPNO BIGINT NOT NULL, TYPE VARCHAR(15), DEPT VARCHAR(15), YEARS_OF_EXP FLOAT,CATEGORY VARCHAR(2),PRIMARY KEY(EMPNO))
INSERT into "DB2SCHEMA".EMPLOYMENT_DETAILS VALUES('SAM',11111,'REGULAR','SALES',4.2,'B')
INSERT into "DB2SCHEMA".EMPLOYMENT_DETAILS VALUES('ALEX',22222,'PARTTIME','HR',19,'E')
INSERT into "DB2SCHEMA".EMPLOYMENT_DETAILS VALUES('LAURA',33333,'REGULAR','MARKETING',1,'A')
drop table "DB2SCHEMA".PAYROLL_DETAILS
create table "DB2SCHEMA".PAYROLL_DETAILS(EMPNAME VARCHAR(25) NOT NULL, EMPNO BIGINT NOT NULL,SALARY DOUBLE, HRA DOUBLE,CONVEYENCE DOUBLE, RETIRALS DOUBLE, OTHER_BENEFITS DOUBLE, PRIMARY KEY(EMPNO))
INSERT into "DB2SCHEMA".PAYROLL_DETAILS VALUES('SAM',11111,28000.00,7000.00, 1600.00,2000.00,0.0)
INSERT into "DB2SCHEMA".PAYROLL_DETAILS VALUES('ALEX',22222,75000.00,18000.00,2400.00,10000.00,0.00)
INSERT into "DB2SCHEMA".PAYROLL_DETAILS VALUES('LAURA',33333,15000.00,3500.00,800.00,1000.00,0.0)
drop procedure db2schema.retrieve_employee_details
CREATE PROCEDURE db2schema.retrieve_employee_details(INOUT emp_name CHAR(25),INOUT emp_no INT, OUT age INT, OUT sex CHAR(10) , OUT marital_status CHAR(10),OUT nationality CHAR(20), OUT type CHAR(15), OUT dept CHAR(15), OUT exp FLOAT,OUT cat CHAR(2),OUT salary DOUBLE,OUT hra DOUBLE, OUT convey DOUBLE, OUT retirals DOUBLE, OUT benefits DOUBLE )LANGUAGE SQL   BEGIN  DECLARE SQLSTATE CHAR(5);DECLARE ben DOUBLE;DECLARE not_found CONDITION FOR SQLSTATE '02000';DECLARE c1 CURSOR FOR SELECT AGE,SEX,MARITAL_STATUS,NATIONALITY FROM "DB2SCHEMA".PERSONAL_DETAILS  WHERE EMPNAME = emp_name AND EMPNO = emp_no; DECLARE c2 CURSOR FOR SELECT TYPE,DEPT,YEARS_OF_EXP,CATEGORY FROM "DB2SCHEMA".EMPLOYMENT_DETAILS  WHERE EMPNAME = emp_name AND EMPNO = emp_no;DECLARE c3 CURSOR FOR SELECT SALARY,HRA,CONVEYENCE,RETIRALS,OTHER_BENEFITS FROM "DB2SCHEMA".PAYROLL_DETAILS  WHERE EMPNAME = emp_name AND EMPNO = emp_no;DECLARE EXIT HANDLER FOR not_found SIGNAL SQLSTATE '20000' SET MESSAGE_TEXT = 'Employee Number not found';Open c1; Fetch c1 into age,sex,marital_status,nationality;Open c2; Fetch c2 into type,dept,exp,cat; Open c3; Fetch c3 into salary,hra,convey,retirals,benefits; if (cat ='A') then SET benefits=2000.00; elseif (cat ='B') then SET benefits=3000.00; elseif (cat ='C') then SET benefits=4000.00; elseif (cat ='D') then SET benefits=5000.00; elseif (cat ='E') then SET benefits=6000.00; else SET benefits=1000.00;end if; SET ben = benefits ;UPDATE "DB2SCHEMA".PAYROLL_DETAILS SET OTHER_BENEFITS = ben WHERE EMPNAME = emp_name AND EMPNO = emp_no;END
Disconnect EMPLOYEE
