connect to LOAN_ACC
drop table "DB2SCHEMA".LOAN_ACCOUNT
create table "DB2SCHEMA".LOAN_ACCOUNT("ACCOUNT_NO" BIGINT NOT NULL, "ACCOUNT_NAME" VARCHAR(50) , "BALANCE" DOUBLE, PRIMARY KEY(ACCOUNT_NO))
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50005,'JOHN',2525000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50006,'PETER',1375000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50007,'ANDREW',237000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50008,'MARY',755000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50009,'DAVID',345000.00)
drop table "DB2SCHEMA".LOAN_ACCOUNT_TRANSACTION
create table "DB2SCHEMA".LOAN_ACCOUNT_TRANSACTION("ACCOUNT_NO" BIGINT NOT NULL, "ACCOUNT_NAME" VARCHAR(50) , "BALANCE" DOUBLE,"TRANSACTION_AMOUNT" DOUBLE, "TRANSACTION_STATUS" VARCHAR(50))
drop procedure db2schema.update_loan_account
CREATE PROCEDURE db2schema.update_loan_account(IN laccount_no INT,IN laccount_name CHAR(50), IN amount FLOAT, OUT balance FLOAT , OUT status CHAR(10)) LANGUAGE SQL   BEGIN  DECLARE SQLSTATE CHAR(5); DECLARE acc_no INT; DECLARE acc_name CHAR(50); DECLARE bal FLOAT; DECLARE stat CHAR(10);DECLARE not_found CONDITION FOR SQLSTATE '02000';DECLARE c1 CURSOR FOR SELECT ACCOUNT_NO, ACCOUNT_NAME , BALANCE FROM "DB2SCHEMA".LOAN_ACCOUNT  WHERE ACCOUNT_NO = laccount_no AND ACCOUNT_NAME = laccount_name; DECLARE EXIT HANDLER FOR not_found SET stat = 'NOT FOUND'; Open c1; Fetch c1 into acc_no,acc_name,bal; if ( amount < bal) then SET bal = bal + amount ;  UPDATE "DB2SCHEMA".LOAN_ACCOUNT SET BALANCE = bal WHERE ACCOUNT_NO = laccount_no; SET stat = 'SUCCESS' ; INSERT into "DB2SCHEMA".LOAN_ACCOUNT_TRANSACTION values (laccount_no,laccount_name,bal,amount,'TRANSACTION COMPLETED SUCCESSFULLY'); else SET stat = 'FAILURE'; end if; SET balance = bal; SET status = stat;END
Disconnect LOAN_ACC


connect to LOAN_ACC
drop table "DB2SCHEMA".LOAN_ACCOUNT
create table "DB2SCHEMA".LOAN_ACCOUNT("ACCOUNT_NO" BIGINT NOT NULL, 
"ACCOUNT_NAME" VARCHAR(50) , "BALANCE" DOUBLE, PRIMARY KEY(ACCOUNT_NO))
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50005,'JOHN',2525000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50006,'PETER',1375000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50007,'ANDREW',237000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50008,'MARY',755000.00)
INSERT into "DB2SCHEMA".LOAN_ACCOUNT VALUES(50009,'DAVID',345000.00)
drop table "DB2SCHEMA".LOAN_ACCOUNT_TRANSACTION
create table "DB2SCHEMA".LOAN_ACCOUNT_TRANSACTION("ACCOUNT_NO" BIGINT NOT NULL, 
"ACCOUNT_NAME" VARCHAR(50) , "BALANCE" DOUBLE,"TRANSACTION_AMOUNT" DOUBLE, 
"TRANSACTION_STATUS" VARCHAR(50))
drop procedure db2schema.update_loan_account
CREATE PROCEDURE db2schema.update_loan_account(IN laccount_no INT,IN laccount_name 
CHAR(50), IN amount FLOAT, OUT balance FLOAT , OUT status CHAR(10)) LANGUAGE SQL
BEGIN  DECLARE SQLSTATE CHAR(5); DECLARE acc_no INT; DECLARE acc_name CHAR(50); DECLARE
bal FLOAT; DECLARE stat CHAR(10);DECLARE not_found CONDITION FOR SQLSTATE '02000';
DECLARE c1 CURSOR FOR SELECT ACCOUNT_NO, ACCOUNT_NAME , BALANCE FROM "DB2SCHEMA".
LOAN_ACCOUNT  WHERE ACCOUNT_NO = laccount_no AND ACCOUNT_NAME = laccount_name; 
DECLARE EXIT HANDLER FOR not_found SET stat = 'NOT FOUND'; Open c1; 
Fetch c1 into acc_no,acc_name,bal; if ( amount < bal) then SET bal = bal + amount ;  
UPDATE "DB2SCHEMA".LOAN_ACCOUNT SET BALANCE = bal WHERE ACCOUNT_NO = laccount_no; 
SET stat = 'SUCCESS' ; INSERT into "DB2SCHEMA".LOAN_ACCOUNT_TRANSACTION values 
(laccount_no,laccount_name,bal,amount,'TRANSACTION COMPLETED SUCCESSFULLY'); 
else SET stat = 'FAILURE'; end if; SET balance = bal; SET status = stat;