connect to MASTER
drop table "DB2SCHEMA".MASTER_TABLE
create table "DB2SCHEMA".MASTER_TABLE(EMPNAME VARCHAR(25) NOT NULL, EMPNO BIGINT NOT NULL,AGE INT, SEX VARCHAR(10),MARITAL_STATUS VARCHAR(10),NATIONALITY VARCHAR (20),TYPE VARCHAR(15), DEPT VARCHAR(15), YEARS_OF_EXP FLOAT,CATEGORY VARCHAR(2),SALARY DOUBLE, HRA DOUBLE,CONVEYENCE DOUBLE, RETIRALS DOUBLE, OTHER_BENEFITS DOUBLE, PRIMARY KEY(EMPNO))
disconnect MASTER