<!--
File EmployeeService.wsdl, application EmployeeService
-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bons1="http://training.ibm.com/Employee" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://EmployeeService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="EmployeeService" targetNamespace="http://EmployeeService">
<wsdl:documentation>
<wsdl:appinfo source="WMQI_APPINFO">
<MRWSDLAppInfo imported="true">
<binding hasEncoding="false" imported="true" name="EmployeeServiceHttpBinding" originalBindingStyle="document"/>
<generatedXSD location="EmployeeService_InlineSchema1.xsd"/>
</MRWSDLAppInfo>
</wsdl:appinfo>
</wsdl:documentation>
<wsdl:types>
<xsd:schema xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions" targetNamespace="http://EmployeeService">
<xsd:import namespace="http://training.ibm.com/Employee" schemaLocation="http://192.168.0.101:7800/EmployeeService?xsd=xsd0"/>
<xsd:include schemaLocation="http://192.168.0.101:7800/EmployeeService?xsd=xsd1"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="getEmployeeRequestMsg">
<wsdl:part element="tns:getEmployee" name="getEmployeeParameters"/>
</wsdl:message>
<wsdl:message name="getEmployeeResponseMsg">
<wsdl:part element="tns:getEmployeeResponse" name="getEmployeeResult"/>
</wsdl:message>
<wsdl:portType name="EmployeeService">
<wsdl:operation name="getEmployee">
<wsdl:input message="tns:getEmployeeRequestMsg" name="getEmployeeRequest"/>
<wsdl:output message="tns:getEmployeeResponseMsg" name="getEmployeeResponse"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="EmployeeServiceHttpBinding" type="tns:EmployeeService">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="getEmployee">
<soap:operation soapAction="http://EmployeeService/getEmployee"/>
<wsdl:input name="getEmployeeRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="getEmployeeResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="EmployeeServiceHttpService">
<wsdl:port binding="tns:EmployeeServiceHttpBinding" name="EmployeeServiceHttpPort">
<soap:address location="http://192.168.0.101:7800/EmployeeService"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>